dataset:
  edge_encoder: false
  edge_encoder_bn: false
  edge_encoder_name: LinearEdge
  format: PyG-TUDataset
  name: DD
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: LapPE
  split_mode: cv-kfold-4
  task: graph
  task_type: classification
  transductive: false
fuzzy:
  fuzzy_head: 3
  fuzzyinvar: 4
  fuzzylayer: 3
  fuzzynum: 0
  fuzzynum_mfs: 3
  fz_mix: oneorder
  fz_rescale: false
  fzdivision_type: random
  fzindim_rate: 1.0
gnn:
  act: relu
  agg: mean
  batchnorm: false
  dim_inner: 18
  dropout: 0.0
  head: default
  layers_post_mp: 3
  layers_pre_mp: 0
  normalize_adj: false
gt:
  attn_dropout: 0.5
  batch_norm: true
  dim_hidden: 18
  dropout: 0.0
  layer_norm: false
  layer_type: None+None
  layers: 2
  n_heads: 2
metric_best: accuracy
model:
  edge_decoding: dot
  graph_pooling: mean
  loss_fun: cross_entropy
  type: FFDNModel
optim:
  base_lr: 0.001
  clip_grad_norm: true
  max_epoch: 100
  optimizer: adam
  weight_decay: 1.0e-05
out_dir: results
posenc_LapPE:
  dim_pe: 2
  eigen:
    eigvec_norm: L2
    laplacian_norm: none
    max_freqs: 8
  enable: true
  layers: 1
  model: DeepSet
  raw_norm_type: none
train:
  batch_size: 2
  ckpt_period: 100
  eval_period: 1
  mode: custom
wandb:
  project: DD
  use: false
